### ISSUE TITLE
How-to install on macOS

### ISSUE THREAD

**Issue by MironChen** [abhijithvijayan/ghost-on-github-pages#28]
HI! Thank you for developing such a great program.

I would like to install it on my Mac, however when I try `sudo apt-get install build-essential`, it told me `command not found: apt-get`, which is not available in macOS, as well as 
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt update && sudo apt install yarn
```

Could you plz tell me how to solve it or if it is possible to install it on Mac?
Thanks!

**Comment by pavle2** [comment]
@MironChen  This is for Debian packages. See [this](https://stackoverflow.com/questions/38086451/how-to-install-build-essential-on-mac).

Once you have brew installed this should be installed already and you can just skip this part on MacOS.

**Comment by MironChen** [comment]
Thanks, I have successfully built it on my Mac. 

Use `brew install yarn` instead of `apt-get` should be work.

**Comment by abhijithvijayan** [comment]
Glad this is sorted out.

This article was written for Ubuntu(when I was using the distro). 

Anyway, closing this for now. feel free to reopen if necessary.
