### ISSUE TITLE
Add a note on disabling two-factor authentication in deploy.sh

### ISSUE THREAD

**Issue by pavlenex** [abhijithvijayan/ghost-on-github-pages#29]
First of all wanted to thank you for a great tool, helped me so much.

Second, it may be a good idea to add in deploy.sh a line which mention two-factor authentication needs to be disabled for it to work. Perhaps it's just me, but I had to disable it so that it could work.

Leaving here as a reference to other as well.

As a side note, perhaps in readme you should node that in deploy.sh nothing has to be altered.  I was a bit confused with `		echo ' -------------------- INFORMATION NEEDED -------------------- '` and took me a few tries to figure out that nothing should be changed there :)

Anyway, thanks so much for the tool once again, keep up the great work.

**Comment by pavlenex** [comment]
Actually it works OK on Windows if you have git installed, was unable to get this working on MacOS. closing this, hopefully it'll help someone who experiences similar issues on MacOS.

**Comment by abhijithvijayan** [comment]
Actually the message was intended as a tag heading in terminal.

Didn't think it would cause ambiguity though.

**Comment by pavlenex** [comment]
Probably a not big deal, hopefully i someone has the same problem, they'll find a solution here. Could be that it only confused me. Actually if you login via GitHub desktop on Windows it works, tried earlier on MacOS and had the issue.
