### ISSUE TITLE
Broken images on Safari mobile

### ISSUE THREAD

**Issue by pavle2** [abhijithvijayan/ghost-on-github-pages#30]
Hi!

For some reason demo images are broken on Safari on mobile. I've replicated with your demo site as well. On desktop it seems to work, which is quite weird.

Any idea what may be causing this? 
Thank you.
![IMG_4994](https://user-images.githubusercontent.com/64681588/80862052-90b28380-8c72-11ea-9de9-43d5cede924a.PNG)

Let me know how I can provide more relevant data to troubleshoot this.

**Comment by pavle2** [comment]
Weird, after disabling VPN on my phone it showed up normally and I can no longer replicate it neither on your blog or on my. Probably a caching issue with Github Pages I assume.

**Comment by abhijithvijayan** [comment]
If GitHub pages is causing stuffs like that. Deploy it to a good provider like netlify.
